### ISSUE TITLE
instructions to run on docker with a custom password ( no token )

### ISSUE THREAD

**Issue by Jarrodsz** [froggleston/freqtrade_analysis_notebook#1]
**note: below example assumes your docker-compose and other files are in the root of /ft_userdata instead of a docker subfolder ( which i have seen in some repros ). you can modify this with the context property in the dockerfile if needed ./docker **

In docker-compose I added this section:

```
  lab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    restart: unless-stopped
    container_name: lab
    ports:
      - "127.0.0.1:8888:8888"
      volumes:
      - "./user_data:/freqtrade/user_data"
      - "./jupyter_config.py:/root/.jupyter/jupyter_notebook_config.py"
      - "./notebook_helper.py:/freqtrade/notebook_helper.py"
      - "./RollingBacktestNotebook.ipynb:/freqtrade/RollingBacktestNotebook.ipynb"
    command: >
      jupyter lab --port=8888 --ip 0.0.0.0 --allow-root --NotebookApp.token=''
```

jupyter_config.py:
```
c.NotebookApp.token = ''
c.NotebookApp.password_required = True
c.NotebookApp.password = '<password_token_here>'
```

Dockerfile.jupyter:
```
FROM freqtradeorg/freqtrade:develop_plot


# Pin jupyter-client to avoid tornado version conflict
RUN pip install jupyterlab jupyter-client==7.3.4 --user --no-cache-dir

# Requirements for freqtrade
RUN pip install tqdm quantstats

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
```

To get the password token run:
```
docker-compose run --rm lab python -c 'from notebook.auth import passwd; print(passwd())'
```
